/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author jose
 */
public class EntornoGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EntornoGUI.class.getName());

    /**
     * Creates new form EntornoGUI
     */
    public EntornoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        primerNumero = new javax.swing.JLabel();
        primerLabel = new javax.swing.JTextField();
        segundoNumero = new javax.swing.JLabel();
        segundoLabel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoLabel = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        tercerNumero = new javax.swing.JLabel();
        tercerLabel = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        primerNumero.setText("Primer Número");

        primerLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerLabelActionPerformed(evt);
            }
        });

        segundoNumero.setText("Segundo Número");

        segundoLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoLabelActionPerformed(evt);
            }
        });

        resultadoLabel.setColumns(20);
        resultadoLabel.setRows(5);
        resultadoLabel.setText("El resultado es:");
        jScrollPane1.setViewportView(resultadoLabel);

        jButton1.setText("Multiplicación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tercerNumero.setText("Tercer Número");

        tercerLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tercerLabelActionPerformed(evt);
            }
        });

        jButton2.setText("Mayor Número");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(segundoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(tercerNumero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tercerLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 282, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(segundoNumero)
                                    .addComponent(primerNumero))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(primerLabel)
                                .addGap(138, 138, 138)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(primerNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(primerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(segundoNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(segundoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tercerNumero))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tercerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void primerLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primerLabelActionPerformed

    private void segundoLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_segundoLabelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String numero1 = primerLabel.getText();
        String numero2 = segundoLabel.getText();
        double resultado;
        
        resultado = Double.parseDouble(numero1) * Double.parseDouble(numero2);
        
        resultadoLabel.setText("El resultado es : " + resultado);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tercerLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tercerLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tercerLabelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double numero1 = Double.parseDouble(primerLabel.getText());
        double numero2 = Double.parseDouble(segundoLabel.getText());
        double numero3 = Double.parseDouble(tercerLabel.getText());
        String text = "";
        if (numero1 == numero2 && numero2 == numero3) {
            text = "El resultado es : Los tres números son iguales";
        } else {
            text += " El mayor número es : ";
            text += String.valueOf(Math.max(numero1, Math.max(numero2, numero3)));
        }
        
        if (numero1 == numero2) {
            text += "\n El número 1 y el número 2 son iguales";
        } else if (numero1 == numero3) {
            text += "\n El número 1 y el número 3 son iguales";
        } else if (numero2 == numero3) {
            text += "\n El número 2 y el número 3 son iguales";
        }
        
        resultadoLabel.setText(text);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EntornoGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField primerLabel;
    private javax.swing.JLabel primerNumero;
    private javax.swing.JTextArea resultadoLabel;
    private javax.swing.JTextField segundoLabel;
    private javax.swing.JLabel segundoNumero;
    private javax.swing.JTextField tercerLabel;
    private javax.swing.JLabel tercerNumero;
    // End of variables declaration//GEN-END:variables
}
